import Header from "../components/Header.jsx"
import Navbar from "../components/Navbar.jsx"


const Home = () => {
  return (
    <div>
      <Navbar/>
      <Header/>
    </div>
  )
}

export default Home                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              